# Generated by Django 3.2.6 on 2022-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=200)),
                ('community', models.CharField(max_length=200)),
                ('oid', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('sensors', models.ManyToManyField(blank=True, to='inventory.Sensor')),
            ],
        ),
    ]
